# Generated by Django 5.1.7 on 2025-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='creator',
        ),
        migrations.AddField(
            model_name='module',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
