# Generated by Django 5.1.7 on 2025-03-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_module_creator_module_creator_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='creator_name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.module')),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
