# Generated by Django 5.1.7 on 2025-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_module_name_remove_module_creator_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='module',
            name='creator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
