# Generated by Django 5.1.7 on 2025-03-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_module_created_at_module_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.RemoveField(
            model_name='module',
            name='user',
        ),
    ]
