# Generated by Django 5.1.7 on 2025-03-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_module_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
